### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by jordannbeattie** [ethercreative/atom#2]
Is (or could) it be possible to nest atoms within nested atoms? 

For example, if you had a `ul` atom and an `li` atom, could you created a multi-level list? 

When I try, it looks like all children are shown on the top-level atom. 

```
{% x:list/ul %}
    {% x:list/li { label: "level 1" } %}
        {% x:list/li { label: "level 2" } %}
    {% endx:list/li %}
{% endx:list/ul %}
```

ul.twig
```
<ul>
    {{ children }}
</ul>
```

li.twig
```
<li>
    <a href="#">{{ label }}</a>
    <ul>
        {{ children }}
    </ul>
</li>
```

**Comment by Tam** [comment]
I don't see why not? Try it and see!
https://github.com/ethercreative/atom#nested

**Comment by jordannbeattie** [comment]
Hi Tam, 

I gave it a try but as I mentioned in the issue, the output seems to include all children in the first `{{ children }}` slot. 

If I do
```
{% x:list/ul %}
    {% x:list/li { label: "level 1" } %}
        {% x:list/li { label: "level 2" } %}
    {% endx:list/li %}
{% endx:list/ul %}
```

The output is
```
<ul>
    <li>
        <a href="#">level 1</a>
    </li>
    <li>
        <a href="#">level 2</a>
    </li>
</ul>
```

So the children put into the `li` atom, ends up being a child of the `ul` item

**Comment by jordannbeattie** [comment]
This must have been something I was doing wrong but still not exactly sure what it was. 

Seems to be working perfectly now that I've done it again in a new project.
